import type { GameRecord } from '@/lib/types/gameContent'

export const CONNECTION_QUEST_GAMES: GameRecord[] = [
  // ── EASY ──────────────────────────────────────────────────────────────────
  {
    id: 'cq-easy-001', gameType: 'connection-quest', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 1, memory: 1, reasoning: 2, speed: 1 },
    source: 'static',
    content: { question: 'Dog is to kennel as bird is to ___?', options: ['Pond', 'Nest', 'Burrow', 'Den'], correct: 'Nest', narrativeWrapper: 'The museum curator sorted animal homes — can you help her?' },
    hint1: 'Where does a bird sleep and raise its chicks?',
    hint2: 'It is made of twigs and sits in a tree.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-easy-002', gameType: 'connection-quest', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 1, memory: 1, reasoning: 2, speed: 1 },
    source: 'static',
    content: { question: 'Cat is to kitten as dog is to ___?', options: ['Puppy', 'Calf', 'Lamb', 'Foal'], correct: 'Puppy', narrativeWrapper: 'Sort the baby animals into their correct family groups!' },
    hint1: 'What do you call a baby dog?',
    hint2: 'It rhymes with "guppy".',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-easy-003', gameType: 'connection-quest', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 1, memory: 1, reasoning: 2, speed: 1 },
    source: 'static',
    content: { question: 'Apple is to fruit as carrot is to ___?', options: ['Meat', 'Vegetable', 'Grain', 'Dairy'], correct: 'Vegetable', narrativeWrapper: 'Help the chef sort the ingredients into the right food groups.' },
    hint1: 'Think about the food pyramid at school.',
    hint2: 'Broccoli and peas belong to the same group as carrot.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-easy-004', gameType: 'connection-quest', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 1, memory: 1, reasoning: 2, speed: 1 },
    source: 'static',
    content: { question: 'Pen is to write as scissors is to ___?', options: ['Draw', 'Cut', 'Paint', 'Glue'], correct: 'Cut', narrativeWrapper: 'The art teacher needs help sorting tools by what they do.' },
    hint1: 'What do scissors do to paper?',
    hint2: 'Snip, snip — they make things shorter.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-easy-005', gameType: 'connection-quest', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 1, memory: 1, reasoning: 2, speed: 1 },
    source: 'static',
    content: { question: 'Sun is to day as moon is to ___?', options: ['Morning', 'Night', 'Afternoon', 'Dusk'], correct: 'Night', narrativeWrapper: 'The astronomer is labelling her sky charts — help her pair the right objects.' },
    hint1: 'When do you see the moon brightest?',
    hint2: 'The opposite of day.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-easy-006', gameType: 'connection-quest', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 1, memory: 1, reasoning: 2, speed: 1 },
    source: 'static',
    content: { question: 'Fish is to swim as bird is to ___?', options: ['Walk', 'Fly', 'Crawl', 'Jump'], correct: 'Fly', narrativeWrapper: 'The explorer\'s field guide matches animals to how they move.' },
    hint1: 'Fish move through water; birds move through…?',
    hint2: 'Birds have wings for a reason.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-easy-007', gameType: 'connection-quest', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 1, memory: 1, reasoning: 2, speed: 1 },
    source: 'static',
    content: { question: 'Shoe is to foot as glove is to ___?', options: ['Head', 'Hand', 'Knee', 'Elbow'], correct: 'Hand', narrativeWrapper: 'The clothes shop needs to sort accessories by the body part they cover.' },
    hint1: 'A glove fits over fingers and a palm.',
    hint2: 'You put it on at the end of your arm.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-easy-008', gameType: 'connection-quest', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 1, memory: 1, reasoning: 2, speed: 1 },
    source: 'static',
    content: { question: 'Doctor is to hospital as teacher is to ___?', options: ['Clinic', 'Library', 'School', 'Stadium'], correct: 'School', narrativeWrapper: 'Match each professional to the building where they work.' },
    hint1: 'Where do children go to learn every day?',
    hint2: 'Teachers stand at the front of a classroom.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-easy-009', gameType: 'connection-quest', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 1, memory: 1, reasoning: 2, speed: 1 },
    source: 'static',
    content: { question: 'Day is to awake as night is to ___?', options: ['Bright', 'Busy', 'Asleep', 'Cold'], correct: 'Asleep', narrativeWrapper: 'The sleep scientist is mapping daily routines. Help her finish the chart.' },
    hint1: 'What do most people do when it gets dark?',
    hint2: 'The opposite of being awake.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-easy-010', gameType: 'connection-quest', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 1, memory: 1, reasoning: 2, speed: 1 },
    source: 'static',
    content: { question: 'Cub is to bear as foal is to ___?', options: ['Cow', 'Horse', 'Sheep', 'Deer'], correct: 'Horse', narrativeWrapper: 'The wildlife park is labelling baby animals with their parents. Help!' },
    hint1: 'A foal is a baby animal with four legs and a mane.',
    hint2: 'It grows up to be ridden or to race.',
    createdAt: '2026-05-19T00:00:00Z',
  },

  // ── MEDIUM ────────────────────────────────────────────────────────────────
  {
    id: 'cq-medium-001', gameType: 'connection-quest', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 2, memory: 1, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: 'Book is to library as painting is to ___?', options: ['School', 'Gallery', 'Stadium', 'Laboratory'], correct: 'Gallery', narrativeWrapper: 'The city planner is mapping where different things belong — help her!' },
    hint1: 'Where do people go to look at art?',
    hint2: 'The Louvre is a famous one in Paris.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-medium-002', gameType: 'connection-quest', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 2, memory: 1, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: 'Ice is to cold as fire is to ___?', options: ['Red', 'Hot', 'Bright', 'Fast'], correct: 'Hot', narrativeWrapper: 'A young scientist is testing opposites in her lab — complete her experiment.' },
    hint1: 'What do you feel when you stand near a campfire?',
    hint2: 'The opposite of cold.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-medium-003', gameType: 'connection-quest', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 2, memory: 1, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: 'Architect is to building as composer is to ___?', options: ['Painting', 'Symphony', 'Sculpture', 'Recipe'], correct: 'Symphony', narrativeWrapper: 'Match each creator to their creation in the Hall of Arts.' },
    hint1: 'A composer creates music.',
    hint2: 'Beethoven and Mozart were famous for this.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-medium-004', gameType: 'connection-quest', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 2, memory: 1, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: 'Caterpillar is to butterfly as tadpole is to ___?', options: ['Fish', 'Frog', 'Lizard', 'Newt'], correct: 'Frog', narrativeWrapper: 'The nature trail guide is explaining metamorphosis — help her match the stages.' },
    hint1: 'What does a tadpole grow into?',
    hint2: 'It croaks and lives near ponds.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-medium-005', gameType: 'connection-quest', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 2, memory: 1, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: 'Telescope is to astronomer as stethoscope is to ___?', options: ['Scientist', 'Doctor', 'Engineer', 'Teacher'], correct: 'Doctor', narrativeWrapper: 'Sort each scientist\'s tool to their correct profession.' },
    hint1: 'Who uses a stethoscope to listen to your heartbeat?',
    hint2: 'You visit them when you are sick.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-medium-006', gameType: 'connection-quest', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 2, memory: 1, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: 'Knife is to chef as scalpel is to ___?', options: ['Dentist', 'Surgeon', 'Carpenter', 'Scientist'], correct: 'Surgeon', narrativeWrapper: 'The medical museum is pairing precision tools with their specialist users.' },
    hint1: 'A scalpel is used in an operating theatre.',
    hint2: 'This specialist performs operations inside the body.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-medium-007', gameType: 'connection-quest', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 2, memory: 1, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: 'Seed is to flower as egg is to ___?', options: ['Bird', 'Chick', 'Nest', 'Wing'], correct: 'Chick', narrativeWrapper: 'The nature cycle exhibit shows before-and-after transformations — finish the display.' },
    hint1: 'What hatches from a bird\'s egg?',
    hint2: 'It is a baby bird covered in soft feathers.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-medium-008', gameType: 'connection-quest', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 2, memory: 1, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: 'Author is to novel as director is to ___?', options: ['Script', 'Stage', 'Film', 'Painting'], correct: 'Film', narrativeWrapper: 'The creative arts hall is matching creators to their final product.' },
    hint1: 'A director shouts "action!" on a movie set.',
    hint2: 'You watch this at the cinema.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-medium-009', gameType: 'connection-quest', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 2, memory: 1, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: 'River is to estuary as mountain is to ___?', options: ['Hill', 'Peak', 'Valley', 'Foothill'], correct: 'Valley', narrativeWrapper: 'The geography teacher is matching terrain features to their adjacent landforms.' },
    hint1: 'A river ends at an estuary; a mountain has a low area between its slopes.',
    hint2: 'Look down from a mountain peak — what is below?',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-medium-010', gameType: 'connection-quest', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 2, memory: 1, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: 'Rain is to flood as drought is to ___?', options: ['Cold', 'Storm', 'Famine', 'Rain'], correct: 'Famine', narrativeWrapper: 'The climate scientist is tracing long-term effects of extreme weather events.' },
    hint1: 'Drought means no rain — crops fail and food becomes scarce.',
    hint2: 'What happens to people\'s food supply when nothing grows?',
    createdAt: '2026-05-19T00:00:00Z',
  },

  // ── HARD ──────────────────────────────────────────────────────────────────
  {
    id: 'cq-hard-001', gameType: 'connection-quest', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 3, memory: 1, reasoning: 4, speed: 1 },
    source: 'static',
    content: { question: 'Symphony is to composer as theorem is to ___?', options: ['Artist', 'Mathematician', 'Poet', 'Architect'], correct: 'Mathematician', narrativeWrapper: 'The Hall of Great Works pairs each creation with its creator — complete the final exhibit.' },
    hint1: 'Pythagoras and Euclid were famous for proving these.',
    hint2: 'A theorem is a proven mathematical statement.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-hard-002', gameType: 'connection-quest', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 3, memory: 1, reasoning: 4, speed: 1 },
    source: 'static',
    content: { question: 'Drought is to famine as inflation is to ___?', options: ['Wealth', 'Poverty', 'Growth', 'Stability'], correct: 'Poverty', narrativeWrapper: 'The economist is mapping cause-and-effect chains — complete her final diagram.' },
    hint1: 'What happens to people\'s purchasing power when prices rise faster than incomes?',
    hint2: 'Drought causes food shortage; inflation causes economic _____.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-hard-003', gameType: 'connection-quest', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 3, memory: 1, reasoning: 4, speed: 1 },
    source: 'static',
    content: { question: 'Chapter is to novel as movement is to ___?', options: ['Poem', 'Symphony', 'Painting', 'Film'], correct: 'Symphony', narrativeWrapper: 'Help the musicologist organise her catalogue of structural terms.' },
    hint1: 'Both a chapter and a movement are structural sub-sections of a larger work.',
    hint2: 'Beethoven\'s Fifth has four of these.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-hard-004', gameType: 'connection-quest', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 3, memory: 1, reasoning: 4, speed: 1 },
    source: 'static',
    content: { question: 'Hypothesis is to experiment as blueprint is to ___?', options: ['Discovery', 'Construction', 'Inspiration', 'Theory'], correct: 'Construction', narrativeWrapper: 'The science fair judge is matching each planning document to its outcome.' },
    hint1: 'A blueprint is the plan for a building.',
    hint2: 'A hypothesis guides an experiment; a blueprint guides a _____.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-hard-005', gameType: 'connection-quest', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 3, memory: 1, reasoning: 4, speed: 1 },
    source: 'static',
    content: { question: 'Antibody is to pathogen as firewall is to ___?', options: ['Virus (computer)', 'Encryption', 'Database', 'Algorithm'], correct: 'Virus (computer)', narrativeWrapper: 'The cybersecurity museum pairs biological and digital defences — help finish the exhibit.' },
    hint1: 'Both an antibody and a firewall are defences against something harmful.',
    hint2: 'A firewall blocks cyber _____ just as an antibody blocks a pathogen.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-hard-006', gameType: 'connection-quest', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 3, memory: 1, reasoning: 4, speed: 1 },
    source: 'static',
    content: { question: 'Latitude is to north-south as longitude is to ___?', options: ['Up-down', 'East-west', 'Depth', 'Distance'], correct: 'East-west', narrativeWrapper: 'The cartography institute is annotating its globe cross-reference system.' },
    hint1: 'Lines of latitude run horizontally around the globe.',
    hint2: 'Lines of longitude run from pole to pole — which direction is that?',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-hard-007', gameType: 'connection-quest', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 3, memory: 1, reasoning: 4, speed: 1 },
    source: 'static',
    content: { question: 'Democracy is to election as monarchy is to ___?', options: ['Revolution', 'Succession', 'Parliament', 'Referendum'], correct: 'Succession', narrativeWrapper: 'The political science archive pairs each system of government with how its leader is chosen.' },
    hint1: 'In a monarchy, the crown passes from parent to child.',
    hint2: 'The word for one ruler following another after death or abdication.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-hard-008', gameType: 'connection-quest', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 3, memory: 1, reasoning: 4, speed: 1 },
    source: 'static',
    content: { question: 'Vaccine is to pathogen as antivirus is to ___?', options: ['Firewall', 'Malware', 'Encryption', 'Server'], correct: 'Malware', narrativeWrapper: 'The cybersecurity museum draws biological analogies for its digital exhibits.' },
    hint1: 'A vaccine defends against a biological threat; antivirus defends against a digital one.',
    hint2: 'Viruses, trojans, and ransomware are all types of this.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-hard-009', gameType: 'connection-quest', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 3, memory: 1, reasoning: 4, speed: 1 },
    source: 'static',
    content: { question: 'Analogy is to comparison as oxymoron is to ___?', options: ['Repetition', 'Contradiction', 'Exaggeration', 'Substitution'], correct: 'Contradiction', narrativeWrapper: 'The rhetoric professor is cataloguing literary devices by their core function.' },
    hint1: '"Deafening silence" is an oxymoron — it combines two opposite ideas.',
    hint2: 'An oxymoron puts two contradictory words together.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'cq-hard-010', gameType: 'connection-quest', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 3, memory: 1, reasoning: 4, speed: 1 },
    source: 'static',
    content: { question: 'Evaporation is to water cycle as photosynthesis is to ___?', options: ['Water cycle', 'Nitrogen cycle', 'Carbon cycle', 'Rock cycle'], correct: 'Carbon cycle', narrativeWrapper: 'The Earth science lab maps each process to the natural cycle it drives.' },
    hint1: 'Photosynthesis takes in CO₂ and releases O₂.',
    hint2: 'The cycle that tracks the movement of carbon through atmosphere, plants, and oceans.',
    createdAt: '2026-05-19T00:00:00Z',
  },
]
