import type { GameRecord } from '@/lib/types/gameContent'

// Sprint 9.3: QWEN generates variants from these seeds
export const GRID_LOGIC_SEEDS: GameRecord[] = [
  {
    id: 'gl-easy-001', gameType: 'grid-logic', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 1, memory: 2, reasoning: 4, speed: 1 },
    source: 'static',
    content: {
      question: 'Three friends (Aisha, Ben, Cara) have three pets (cat, dog, fish). Aisha has the cat. Ben does not have the fish. Who has the dog?',
      options: ['Aisha', 'Ben', 'Cara'],
      correct: 'Ben',
      narrativeWrapper: 'The pet show organiser lost the entries. Help her match each child to their pet!',
    },
    hint1: 'Start with what you know for certain: Aisha has the cat.',
    hint2: 'If Ben does not have the fish, and Aisha has the cat, what is left for Ben?',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'gl-easy-002', gameType: 'grid-logic', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 1, memory: 2, reasoning: 4, speed: 1 },
    source: 'static',
    content: {
      question: 'Three boxes (red, blue, green) hold three fruits (apple, banana, cherry). The red box has the apple. The green box does not have the banana. What is in the blue box?',
      options: ['Apple', 'Banana', 'Cherry'],
      correct: 'Banana',
      narrativeWrapper: 'The market stall owner needs to label her boxes. Use the clues to help!',
    },
    hint1: 'The red box is already solved — cross it off.',
    hint2: 'If green doesn\'t have banana, green has cherry. So blue has…',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'gl-easy-003', gameType: 'grid-logic', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 1, memory: 2, reasoning: 4, speed: 1 },
    source: 'static',
    content: {
      question: 'Four children sit in a row. Tom is not first. Sara is last. Alex is before Tom. Who is first?',
      options: ['Tom', 'Sara', 'Alex', 'Cannot tell'],
      correct: 'Alex',
      narrativeWrapper: 'The class is lining up for the photo. Who stands at the front?',
    },
    hint1: 'Sara is last — place her at position 4.',
    hint2: 'Alex is before Tom, and Tom is not first — so Alex must be first.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'gl-easy-004', gameType: 'grid-logic', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 1, memory: 2, reasoning: 4, speed: 1 },
    source: 'static',
    content: {
      question: 'Three shapes (circle, square, triangle) are coloured (red, blue, yellow). The circle is red. The square is not yellow. What colour is the triangle?',
      options: ['Red', 'Blue', 'Yellow'],
      correct: 'Yellow',
      narrativeWrapper: 'The art teacher is colouring shapes for the display. Help her finish!',
    },
    hint1: 'Circle = red. That leaves blue and yellow for square and triangle.',
    hint2: 'Square is not yellow, so square is blue. Triangle is…',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'gl-easy-005', gameType: 'grid-logic', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 1, memory: 2, reasoning: 4, speed: 1 },
    source: 'static',
    content: {
      question: 'Two lights (left, right) can be on or off. At least one is on. The left light is not on. Which light is on?',
      options: ['Left', 'Right', 'Both', 'Neither'],
      correct: 'Right',
      narrativeWrapper: 'The control panel has two lights. Use the rules to find which one is active.',
    },
    hint1: 'Left is not on. At least one must be on.',
    hint2: 'If left is off and at least one is on, it must be right.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'gl-medium-001', gameType: 'grid-logic', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 1, memory: 3, reasoning: 5, speed: 1 },
    source: 'static',
    content: {
      question: 'Four people (Ali, Beth, Cam, Dana) each like a different sport (football, tennis, swimming, cycling). Ali likes football. Beth does not like tennis. Cam likes swimming. Who likes tennis?',
      options: ['Ali', 'Beth', 'Cam', 'Dana'],
      correct: 'Dana',
      narrativeWrapper: 'The sports club is assigning coaches to their favourite sports. Use the clues!',
    },
    hint1: 'Cross off Ali (football) and Cam (swimming) — they are placed.',
    hint2: 'Beth doesn\'t like tennis, so the only person left for tennis is Dana.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'gl-medium-002', gameType: 'grid-logic', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 1, memory: 3, reasoning: 5, speed: 1 },
    source: 'static',
    content: {
      question: 'Five houses in a row are red, blue, green, yellow, white. The red house is first. The green house is next to the white house. The blue house is between red and green. What position is green?',
      options: ['2nd', '3rd', '4th', '5th'],
      correct: '4th',
      narrativeWrapper: 'The street planner needs to finalise the house colours. Figure out the order!',
    },
    hint1: 'Red=1st, Blue=2nd (between red and green).',
    hint2: 'Green and white are adjacent. If blue=2, green can be 3rd, 4th, or 5th.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'gl-medium-003', gameType: 'grid-logic', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 1, memory: 3, reasoning: 5, speed: 1 },
    source: 'static',
    content: {
      question: 'Three brothers are different ages: 8, 10, 12. The oldest is not Jake. The youngest is Sam. How old is Jake?',
      options: ['8', '10', '12', 'Cannot tell'],
      correct: '10',
      narrativeWrapper: 'The birthday planner needs to know each brother\'s age. Use the clues!',
    },
    hint1: 'Sam = 8 (youngest). The oldest (12) is not Jake.',
    hint2: 'That leaves 10 or 12 for Jake. Since 12 is not Jake, Jake is 10.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'gl-medium-004', gameType: 'grid-logic', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 1, memory: 3, reasoning: 5, speed: 1 },
    source: 'static',
    content: {
      question: 'Four items (book, pen, ruler, eraser) are in four drawers (1, 2, 3, 4). The pen is in drawer 2. The book is not in drawer 1 or 3. The ruler is in drawer 1. Where is the book?',
      options: ['Drawer 1', 'Drawer 2', 'Drawer 3', 'Drawer 4'],
      correct: 'Drawer 4',
      narrativeWrapper: 'The teacher\'s desk has four drawers and she can\'t remember what is where.',
    },
    hint1: 'Ruler=1, Pen=2 are fixed. Book is not in 1 or 3.',
    hint2: 'Book is not 1, not 3, not 2 (pen is there). So book must be in…',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'gl-medium-005', gameType: 'grid-logic', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 1, memory: 3, reasoning: 5, speed: 1 },
    source: 'static',
    content: {
      question: 'Five students scored 60, 70, 75, 80, 90. Priya scored higher than Omar. Omar scored exactly 75. Lena scored the highest. What did Priya score?',
      options: ['70', '75', '80', '90'],
      correct: '80',
      narrativeWrapper: 'The teacher is ranking the test scores. Fill in the missing result!',
    },
    hint1: 'Omar=75. Priya > 75 but Lena has the highest (90).',
    hint2: 'The only score above 75 that is not 90 is 80.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'gl-hard-001', gameType: 'grid-logic', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 2, memory: 4, reasoning: 5, speed: 1 },
    source: 'static',
    content: {
      question: 'Six people sit around a round table. Ana is opposite Ben. Cara is between Ana and Dan. Eli is not next to Ana. Where does Fay sit relative to Ben?',
      options: ['Next to Ben', 'Opposite Ben', 'Between Cara and Eli', 'Cannot be determined'],
      correct: 'Next to Ben',
      narrativeWrapper: 'The dinner party host is finalising the seating plan. Complete it!',
    },
    hint1: 'In a round table of 6, "opposite" means 3 seats apart.',
    hint2: 'Place Ana and Ben opposite. Add Cara between Ana and Dan. Eli avoids Ana. Fay fills the remaining seat next to Ben.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'gl-hard-002', gameType: 'grid-logic', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 2, memory: 4, reasoning: 5, speed: 1 },
    source: 'static',
    content: {
      question: 'Five trains depart at 7am, 8am, 9am, 10am, 11am. Train A is not first or last. Train B departs 2 hours before Train C. Train D departs at 9am. At what time does Train B depart?',
      options: ['7am', '8am', '9am', '10am'],
      correct: '8am',
      narrativeWrapper: 'The station master is completing the departure board. Find Train B\'s time!',
    },
    hint1: 'D=9am. A is not 7am or 11am — A could be 8, 9, or 10.',
    hint2: 'B is 2 hours before C. Possible pairs: (7,9) (8,10) (9,11). D=9 so B≠7. A≠8 leaves B=8.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'gl-hard-003', gameType: 'grid-logic', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 2, memory: 4, reasoning: 5, speed: 1 },
    source: 'static',
    content: {
      question: 'Four boxes weigh 1kg, 2kg, 3kg, 4kg. Box A is heavier than Box B. Box C is lighter than Box B. Box D is the heaviest. What is Box A\'s weight?',
      options: ['1kg', '2kg', '3kg', '4kg'],
      correct: '3kg',
      narrativeWrapper: 'The warehouse robot needs to stack boxes in weight order. Help it!',
    },
    hint1: 'D is heaviest = 4kg. C < B < A.',
    hint2: 'C < B < A < D(4). The only trio where each is strictly less: C=1, B=2, A=3.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'gl-hard-004', gameType: 'grid-logic', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 2, memory: 4, reasoning: 5, speed: 1 },
    source: 'static',
    content: {
      question: 'Three statements about a number: (1) It is even. (2) It is greater than 15. (3) It is less than 20. (4) It is divisible by 3. Which number satisfies all four?',
      options: ['16', '18', '20', '14'],
      correct: '18',
      narrativeWrapper: 'The number vault opens only when all four conditions are met. Find the code!',
    },
    hint1: 'Even and divisible by 3 means divisible by 6.',
    hint2: 'Multiples of 6 between 15 and 20: only 18.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'gl-hard-005', gameType: 'grid-logic', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 2, memory: 4, reasoning: 5, speed: 1 },
    source: 'static',
    content: {
      question: 'Five planets (Mercury, Venus, Earth, Mars, Jupiter) are ranked by distance from the sun. Earth is 3rd. Venus is closer than Earth but farther than Mercury. Jupiter is farthest. What rank is Mars?',
      options: ['2nd', '3rd', '4th', '5th'],
      correct: '4th',
      narrativeWrapper: 'The space academy is ordering the planets by distance. Complete the ranking!',
    },
    hint1: 'Mercury=1, Venus=2, Earth=3 are confirmed. Jupiter=5.',
    hint2: 'Only Mars is left — it must be 4th.',
    createdAt: '2026-05-19T00:00:00Z',
  },
]
