import type { GameRecord } from '@/lib/types/gameContent'

export const MEMORY_FLIP_GAMES: GameRecord[] = [
  // ── EASY (2×2 grid, 2 pairs) ──────────────────────────────────────────────
  {
    id: 'mf-easy-001', gameType: 'memory-flip', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 0, memory: 3, reasoning: 1, speed: 2 },
    source: 'static',
    content: { question: 'Match the animal pairs!', options: ['🐶', '🐱', '🐶', '🐱'], correct: 'all-matched', narrativeWrapper: 'Help Noah match all the animals before the ark sets sail!' },
    hint1: 'Start with the corners — they are easier to remember.',
    hint2: 'Try to find one matching pair at a time.',
    seed: 'mf-easy-001-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-easy-002', gameType: 'memory-flip', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 0, memory: 3, reasoning: 1, speed: 2 },
    source: 'static',
    content: { question: 'Match the shape pairs!', options: ['⭐', '🔵', '⭐', '🔵'], correct: 'all-matched', narrativeWrapper: 'The shape sorter robot needs your help matching its blocks.' },
    hint1: 'Close your eyes for 2 seconds after each flip.',
    hint2: 'Remember where the star is.',
    seed: 'mf-easy-002-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-easy-003', gameType: 'memory-flip', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 0, memory: 3, reasoning: 1, speed: 2 },
    source: 'static',
    content: { question: 'Match the fruit pairs!', options: ['🍎', '🍌', '🍎', '🍌'], correct: 'all-matched', narrativeWrapper: 'The fruit market stall needs to be reorganised. Pair everything up!' },
    hint1: 'The apple and banana are the only fruits here.',
    hint2: 'Once you find one pair, you only have one left.',
    seed: 'mf-easy-003-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-easy-004', gameType: 'memory-flip', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 0, memory: 3, reasoning: 1, speed: 2 },
    source: 'static',
    content: { question: 'Match the colour pairs!', options: ['🔴', '🟡', '🔴', '🟡'], correct: 'all-matched', narrativeWrapper: 'The painter spilled all her colours. Sort them back into pairs!' },
    hint1: 'There are only two colours here.',
    hint2: 'Red and yellow are both warm colours.',
    seed: 'mf-easy-004-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-easy-005', gameType: 'memory-flip', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 0, memory: 3, reasoning: 1, speed: 2 },
    source: 'static',
    content: { question: 'Match the weather pairs!', options: ['☀️', '🌧️', '☀️', '🌧️'], correct: 'all-matched', narrativeWrapper: 'The weather station cards got mixed up. Put them back in pairs!' },
    hint1: 'Sun and rain are the only weather types.',
    hint2: 'You have already found the sun — find its twin.',
    seed: 'mf-easy-005-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-easy-006', gameType: 'memory-flip', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 0, memory: 3, reasoning: 1, speed: 2 },
    source: 'static',
    content: { question: 'Match the transport pairs!', options: ['🚗', '✈️', '🚗', '✈️'], correct: 'all-matched', narrativeWrapper: 'The travel agent lost her booking cards! Pair each vehicle with its duplicate.' },
    hint1: 'There are only two types of transport here.',
    hint2: 'The car stays on roads; the plane goes in the air.',
    seed: 'mf-easy-006-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-easy-007', gameType: 'memory-flip', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 0, memory: 3, reasoning: 1, speed: 2 },
    source: 'static',
    content: { question: 'Match the space object pairs!', options: ['🌙', '⭐', '🌙', '⭐'], correct: 'all-matched', narrativeWrapper: 'Mission Control needs you to match the space cards before the rocket launches!' },
    hint1: 'The moon and a star are the only objects.',
    hint2: 'One shines with its own light; one reflects the sun.',
    seed: 'mf-easy-007-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-easy-008', gameType: 'memory-flip', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 0, memory: 3, reasoning: 1, speed: 2 },
    source: 'static',
    content: { question: 'Match the insect pairs!', options: ['🐝', '🦋', '🐝', '🦋'], correct: 'all-matched', narrativeWrapper: 'The nature scientist is photographing insect pairs. Help her match the duplicates!' },
    hint1: 'A bee and a butterfly — spot them both.',
    hint2: 'Once you find the bee, look for its twin.',
    seed: 'mf-easy-008-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-easy-009', gameType: 'memory-flip', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 0, memory: 3, reasoning: 1, speed: 2 },
    source: 'static',
    content: { question: 'Match the food pairs!', options: ['🍕', '🍔', '🍕', '🍔'], correct: 'all-matched', narrativeWrapper: 'The restaurant menu cards fell off the board. Match each dish to its duplicate!' },
    hint1: 'Pizza and burger — two very different shapes.',
    hint2: 'The round one and the stacked one.',
    seed: 'mf-easy-009-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-easy-010', gameType: 'memory-flip', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 0, memory: 3, reasoning: 1, speed: 2 },
    source: 'static',
    content: { question: 'Match the sport pairs!', options: ['⚽', '🏀', '⚽', '🏀'], correct: 'all-matched', narrativeWrapper: 'The sports shop window display got mixed up. Pair the equipment cards!' },
    hint1: 'A football and a basketball — both are balls but different sizes.',
    hint2: 'Which ball is kicked? Which is thrown?',
    seed: 'mf-easy-010-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },

  // ── MEDIUM (3×4 grid, 6 pairs) ────────────────────────────────────────────
  {
    id: 'mf-medium-001', gameType: 'memory-flip', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 0, memory: 4, reasoning: 1, speed: 3 },
    source: 'static',
    content: { question: 'Match 6 planet pairs in a 3×4 grid!', options: [], correct: 'all-matched', narrativeWrapper: 'Mission Control lost the planet labels. Help the astronaut match them before launch!' },
    hint1: 'Start by flipping two cards in the same row.',
    hint2: 'Remember: Mars was in the top row.',
    seed: 'mf-medium-001-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-medium-002', gameType: 'memory-flip', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 0, memory: 4, reasoning: 1, speed: 3 },
    source: 'static',
    content: { question: 'Match 6 ocean creature pairs!', options: [], correct: 'all-matched', narrativeWrapper: 'The deep-sea biologist needs help identifying creatures in her underwater photo grid.' },
    hint1: 'The octopus was near the middle.',
    hint2: 'Try to map out a mental grid before your next flip.',
    seed: 'mf-medium-002-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-medium-003', gameType: 'memory-flip', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 0, memory: 4, reasoning: 1, speed: 3 },
    source: 'static',
    content: { question: 'Match 6 musical instrument pairs!', options: [], correct: 'all-matched', narrativeWrapper: 'The orchestra\'s instrument cards are all mixed up before the concert. Sort them fast!' },
    hint1: 'Group by string / wind / percussion in your mind.',
    hint2: 'The violin was in the bottom left area.',
    seed: 'mf-medium-003-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-medium-004', gameType: 'memory-flip', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 0, memory: 4, reasoning: 1, speed: 3 },
    source: 'static',
    content: { question: 'Match 6 flag pairs from around the world!', options: [], correct: 'all-matched', narrativeWrapper: 'The geography teacher\'s flag flashcards fell on the floor. Rescue them!' },
    hint1: 'Look for the flag with the most red — it was near the top.',
    hint2: 'Divide the grid into two halves and focus on one half at a time.',
    seed: 'mf-medium-004-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-medium-005', gameType: 'memory-flip', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 0, memory: 4, reasoning: 1, speed: 3 },
    source: 'static',
    content: { question: 'Match 6 dinosaur pairs!', options: [], correct: 'all-matched', narrativeWrapper: 'The palaeontologist dug up 12 fossils. Match each dinosaur to its duplicate!' },
    hint1: 'The T-Rex was in the second row.',
    hint2: 'Triceratops and Stegosaurus look different — start with those.',
    seed: 'mf-medium-005-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-medium-006', gameType: 'memory-flip', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 0, memory: 4, reasoning: 1, speed: 3 },
    source: 'static',
    content: { question: 'Match 6 world landmark pairs!', options: [], correct: 'all-matched', narrativeWrapper: 'The travel blogger is organising her photo albums. Match each landmark to its duplicate.' },
    hint1: 'The Eiffel Tower was in the top row — it has a distinctive triangular shape.',
    hint2: 'Focus on landmarks with strong silhouettes; they are easiest to remember.',
    seed: 'mf-medium-006-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-medium-007', gameType: 'memory-flip', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 0, memory: 4, reasoning: 1, speed: 3 },
    source: 'static',
    content: { question: 'Match 6 body organ pairs!', options: [], correct: 'all-matched', narrativeWrapper: 'The anatomy class lost the organ model labels. Put them back in matched pairs!' },
    hint1: 'The heart and lungs are easy to spot — find them first.',
    hint2: 'Pair the two symmetric organs (both lungs, both kidneys) as your anchor.',
    seed: 'mf-medium-007-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-medium-008', gameType: 'memory-flip', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 0, memory: 4, reasoning: 1, speed: 3 },
    source: 'static',
    content: { question: 'Match 6 sport-equipment pairs!', options: [], correct: 'all-matched', narrativeWrapper: 'The PE teacher\'s equipment flashcards are all jumbled up. Sort them into matching pairs!' },
    hint1: 'The football was in the left half of the grid.',
    hint2: 'Racket sports all have similar shapes — look carefully at the details.',
    seed: 'mf-medium-008-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-medium-009', gameType: 'memory-flip', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 0, memory: 4, reasoning: 1, speed: 3 },
    source: 'static',
    content: { question: 'Match 6 weather phenomenon pairs!', options: [], correct: 'all-matched', narrativeWrapper: 'The meteorologist\'s observation cards fell off the whiteboard. Help her reorganise them!' },
    hint1: 'Start with the most visually distinctive card — lightning is easy to remember.',
    hint2: 'Rain and snow look similar — look closely at the card details.',
    seed: 'mf-medium-009-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-medium-010', gameType: 'memory-flip', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 0, memory: 4, reasoning: 1, speed: 3 },
    source: 'static',
    content: { question: 'Match 6 geometric shape pairs!', options: [], correct: 'all-matched', narrativeWrapper: 'The geometry teacher\'s shape tiles are all mixed up before the lesson. Sort them fast!' },
    hint1: 'The hexagon was near the centre — it has the most sides.',
    hint2: 'Group by number of sides: triangle (3), square (4), pentagon (5), hexagon (6).',
    seed: 'mf-medium-010-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },

  // ── HARD (4×4 grid, 8 pairs) ──────────────────────────────────────────────
  {
    id: 'mf-hard-001', gameType: 'memory-flip', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 0, memory: 5, reasoning: 1, speed: 4 },
    source: 'static',
    content: { question: 'Match 8 element-symbol pairs in a 4×4 grid!', options: [], correct: 'all-matched', narrativeWrapper: 'The chemistry lab display case got shuffled. Match each element to its symbol before class!' },
    hint1: 'H for hydrogen and O for oxygen are easy starting points.',
    hint2: 'Divide the grid into quadrants — tackle one quadrant at a time.',
    seed: 'mf-hard-001-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-hard-002', gameType: 'memory-flip', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 0, memory: 5, reasoning: 1, speed: 4 },
    source: 'static',
    content: { question: 'Match 8 country-capital pairs in a 4×4 grid!', options: [], correct: 'all-matched', narrativeWrapper: 'The world map museum exhibit got scrambled. Match every country to its capital city!' },
    hint1: 'France-Paris and Japan-Tokyo are the easiest.',
    hint2: 'Focus on countries whose capitals share the first letter.',
    seed: 'mf-hard-002-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-hard-003', gameType: 'memory-flip', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 0, memory: 5, reasoning: 1, speed: 4 },
    source: 'static',
    content: { question: 'Match 8 inventor-invention pairs in a 4×4 grid!', options: [], correct: 'all-matched', narrativeWrapper: 'The invention timeline exhibition is all out of order. Fix it before the doors open!' },
    hint1: 'Edison-lightbulb and Bell-telephone are the most recognisable.',
    hint2: 'Work from the inventors you know best outward.',
    seed: 'mf-hard-003-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-hard-004', gameType: 'memory-flip', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 0, memory: 5, reasoning: 1, speed: 4 },
    source: 'static',
    content: { question: 'Match 8 math-term-definition pairs in a 4×4 grid!', options: [], correct: 'all-matched', narrativeWrapper: 'The maths professor lost all her flashcard pairs! Sort them out before the lecture.' },
    hint1: 'Start with the most visual terms — triangle, circle.',
    hint2: 'If you see "perpendicular" flip it first — it is memorable.',
    seed: 'mf-hard-004-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-hard-005', gameType: 'memory-flip', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 0, memory: 5, reasoning: 1, speed: 4 },
    source: 'static',
    content: { question: 'Match 8 literary-device pairs in a 4×4 grid!', options: [], correct: 'all-matched', narrativeWrapper: 'The English teacher\'s poetry toolkit is all mixed up. Put every device back with its example!' },
    hint1: 'Simile and metaphor are easy to spot — look for "like" or "as".',
    hint2: 'Alliteration always starts with matching letters — spot it quickly.',
    seed: 'mf-hard-005-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-hard-006', gameType: 'memory-flip', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 0, memory: 5, reasoning: 1, speed: 4 },
    source: 'static',
    content: { question: 'Match 8 Greek god-domain pairs in a 4×4 grid!', options: [], correct: 'all-matched', narrativeWrapper: 'The mythology museum needs to match each god to their domain before the tour begins!' },
    hint1: 'Zeus (sky) and Poseidon (sea) are the most famous — find them first.',
    hint2: 'Work from the gods you know best, then narrow down the remaining pairs.',
    seed: 'mf-hard-006-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-hard-007', gameType: 'memory-flip', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 0, memory: 5, reasoning: 1, speed: 4 },
    source: 'static',
    content: { question: 'Match 8 historical figure-achievement pairs in a 4×4 grid!', options: [], correct: 'all-matched', narrativeWrapper: 'The history hall of fame mixed up all its achievement plaques. Restore them!' },
    hint1: 'Einstein-relativity and Newton-gravity are the easiest starting pairs.',
    hint2: 'If you know the field (science, art, politics), use that to narrow down.',
    seed: 'mf-hard-007-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-hard-008', gameType: 'memory-flip', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 0, memory: 5, reasoning: 1, speed: 4 },
    source: 'static',
    content: { question: 'Match 8 proverb-meaning pairs in a 4×4 grid!', options: [], correct: 'all-matched', narrativeWrapper: 'The wisdom wall lost all its explanation cards. Match each proverb to its meaning!' },
    hint1: '"Every cloud has a silver lining" is a well-known proverb — find its meaning first.',
    hint2: 'Read the proverb fully before guessing — the meaning restates the core idea.',
    seed: 'mf-hard-008-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-hard-009', gameType: 'memory-flip', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 0, memory: 5, reasoning: 1, speed: 4 },
    source: 'static',
    content: { question: 'Match 8 currency-country pairs in a 4×4 grid!', options: [], correct: 'all-matched', narrativeWrapper: 'The international bank mixed up its currency display cards. Sort them back out!' },
    hint1: 'Dollar-USA and Pound-UK are the most recognisable pairs.',
    hint2: 'European currencies that are not the Euro are the trickiest — tackle them last.',
    seed: 'mf-hard-009-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'mf-hard-010', gameType: 'memory-flip', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 0, memory: 5, reasoning: 1, speed: 4 },
    source: 'static',
    content: { question: 'Match 8 author-novel pairs in a 4×4 grid!', options: [], correct: 'all-matched', narrativeWrapper: 'The library\'s author spotlight fell off the shelves. Match each writer to their most famous novel!' },
    hint1: 'Tolkien-Lord of the Rings and Rowling-Harry Potter are the easiest pairs.',
    hint2: 'Classic authors (Austen, Dickens, Orwell) each wrote a small number of famous novels — tackle them after the modern ones.',
    seed: 'mf-hard-010-seed',
    createdAt: '2026-05-19T00:00:00Z',
  },
]
