import type { GameRecord } from '@/lib/types/gameContent'

// Sprint 9.3: QWEN generates variants from these seeds
export const PATTERN_BUILDER_SEEDS: GameRecord[] = [
  {
    id: 'pb-easy-001', gameType: 'pattern-builder', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 0, memory: 2, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: '🔴 🔵 🔴 🔵 🔴 ___', options: ['🔴', '🔵', '🟡', '🟢'], correct: '🔵', narrativeWrapper: 'The bead necklace maker needs your help finishing the pattern.' },
    hint1: 'Look at every other bead — what colour is it?',
    hint2: 'Red, Blue, Red, Blue... what comes next?',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'pb-easy-002', gameType: 'pattern-builder', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 0, memory: 2, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: '⭐ ⭐ 🔵 ⭐ ⭐ ___', options: ['⭐', '🔵', '🟡', '🔴'], correct: '🔵', narrativeWrapper: 'The tile layer needs you to finish the floor pattern.' },
    hint1: 'Count the stars between each circle.',
    hint2: 'Two stars, then one circle — repeating.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'pb-easy-003', gameType: 'pattern-builder', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 0, memory: 2, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: '1  2  1  2  1  ___', options: ['1', '2', '3', '0'], correct: '2', narrativeWrapper: 'The robot arm alternates between two settings. What comes next?' },
    hint1: 'The numbers alternate: 1, 2, 1, 2...',
    hint2: 'After a 1, what always comes?',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'pb-easy-004', gameType: 'pattern-builder', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 0, memory: 2, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: '🐱 🐶 🐱 🐶 🐱 ___', options: ['🐱', '🐶', '🐦', '🐟'], correct: '🐶', narrativeWrapper: 'The pet shop puts cats and dogs on alternate shelves — which comes next?' },
    hint1: 'Cat, dog, cat, dog...',
    hint2: 'After a cat always comes a _____.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'pb-easy-005', gameType: 'pattern-builder', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 0, memory: 2, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: '🔺 🔺 🔵 🔺 🔺 ___', options: ['🔺', '🔵', '🟡', '🔶'], correct: '🔵', narrativeWrapper: 'The mosaicist needs the next tile. Complete the pattern!' },
    hint1: 'Two triangles, then one circle — repeating.',
    hint2: 'What comes after every second triangle?',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'pb-medium-001', gameType: 'pattern-builder', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 0, memory: 2, reasoning: 4, speed: 1 },
    source: 'static',
    content: { question: '2  4  6  8  ___', options: ['9', '10', '11', '12'], correct: '10', narrativeWrapper: 'The number train is counting up. What is the next stop?' },
    hint1: 'Each number increases by the same amount.',
    hint2: 'What is 8 + 2?',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'pb-medium-002', gameType: 'pattern-builder', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 0, memory: 2, reasoning: 4, speed: 1 },
    source: 'static',
    content: { question: '1  3  6  10  ___', options: ['13', '14', '15', '16'], correct: '15', narrativeWrapper: 'The triangular number machine is generating a sequence. What comes next?' },
    hint1: 'Look at the differences: +2, +3, +4...',
    hint2: '10 + 5 = ?',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'pb-medium-003', gameType: 'pattern-builder', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 0, memory: 2, reasoning: 4, speed: 1 },
    source: 'static',
    content: { question: '🔴 🔵 🟡 🔴 🔵 ___', options: ['🔴', '🔵', '🟡', '🟢'], correct: '🟡', narrativeWrapper: 'The traffic light factory tests its lenses in a repeating cycle.' },
    hint1: 'The pattern repeats every 3 colours.',
    hint2: 'Red, Blue, Yellow — what position is the 6th bead?',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'pb-medium-004', gameType: 'pattern-builder', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 0, memory: 2, reasoning: 4, speed: 1 },
    source: 'static',
    content: { question: 'A  B  B  A  B  B  ___', options: ['A', 'B', 'C', 'D'], correct: 'A', narrativeWrapper: 'The code-key machine is generating access codes with a hidden pattern.' },
    hint1: 'Look at the pattern length: A, B, B repeats.',
    hint2: 'After every B, B comes a _____.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'pb-medium-005', gameType: 'pattern-builder', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 0, memory: 2, reasoning: 4, speed: 1 },
    source: 'static',
    content: { question: '3  6  12  24  ___', options: ['36', '48', '36', '48'], correct: '48', narrativeWrapper: 'The doubling machine keeps multiplying. What does it produce next?' },
    hint1: 'Each number is double the previous one.',
    hint2: 'What is 24 × 2?',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'pb-hard-001', gameType: 'pattern-builder', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 0, memory: 3, reasoning: 5, speed: 1 },
    source: 'static',
    content: { question: '1  1  2  3  5  8  ___', options: ['11', '12', '13', '14'], correct: '13', narrativeWrapper: 'The spiral galaxy computer is computing the next number in its growth sequence.' },
    hint1: 'Add the last two numbers together.',
    hint2: '5 + 8 = ?',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'pb-hard-002', gameType: 'pattern-builder', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 0, memory: 3, reasoning: 5, speed: 1 },
    source: 'static',
    content: { question: '2  6  12  20  30  ___', options: ['40', '42', '44', '46'], correct: '42', narrativeWrapper: 'The polygon factory counts sides × vertices. Spot the rule!' },
    hint1: 'Look at the differences: +4, +6, +8, +10...',
    hint2: '30 + 12 = ?',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'pb-hard-003', gameType: 'pattern-builder', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 0, memory: 3, reasoning: 5, speed: 1 },
    source: 'static',
    content: { question: 'AB  BA  ABB  BBA  ABBB  ___', options: ['BBBA', 'ABBA', 'BBAB', 'AABB'], correct: 'BBBA', narrativeWrapper: 'The cryptography machine mirrors and extends patterns. Decode the rule!' },
    hint1: 'Each pair mirrors and adds one extra B.',
    hint2: 'ABBB mirrors to _____BB_.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'pb-hard-004', gameType: 'pattern-builder', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 0, memory: 3, reasoning: 5, speed: 1 },
    source: 'static',
    content: { question: '1  4  9  16  25  ___', options: ['30', '34', '36', '40'], correct: '36', narrativeWrapper: 'The square-tile factory lays tiles in square arrays. How many in the next array?' },
    hint1: 'These are perfect squares: 1², 2², 3²...',
    hint2: 'What is 6²?',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'pb-hard-005', gameType: 'pattern-builder', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 0, memory: 3, reasoning: 5, speed: 1 },
    source: 'static',
    content: { question: '2  3  5  7  11  ___', options: ['12', '13', '14', '15'], correct: '13', narrativeWrapper: 'The prime-number sieve machine is outputting primes. What comes next?' },
    hint1: 'All numbers in this sequence have exactly two factors.',
    hint2: 'What prime number comes after 11?',
    createdAt: '2026-05-19T00:00:00Z',
  },
]
