import type { GameRecord } from '@/lib/types/gameContent'

export const WORD_POP_GAMES: GameRecord[] = [
  // ── EASY ──────────────────────────────────────────────────────────────────
  {
    id: 'wp-easy-001', gameType: 'word-pop', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 2, memory: 1, reasoning: 1, speed: 1 },
    source: 'static',
    content: { question: 'What does "happy" mean?', options: ['Sad', 'Joyful', 'Tired', 'Angry'], correct: 'Joyful', narrativeWrapper: 'The puppy looked very _____ when it found its favourite toy.' },
    hint1: 'Think about how you feel on your birthday.',
    hint2: 'It is the opposite of sad.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-easy-002', gameType: 'word-pop', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 2, memory: 1, reasoning: 1, speed: 1 },
    source: 'static',
    content: { question: 'What does "big" mean?', options: ['Tiny', 'Fast', 'Large', 'Quiet'], correct: 'Large', narrativeWrapper: 'The elephant was so _____ it blocked the whole path.' },
    hint1: 'Think about how an elephant compares to a mouse.',
    hint2: 'It is the opposite of tiny.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-easy-003', gameType: 'word-pop', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 2, memory: 1, reasoning: 1, speed: 1 },
    source: 'static',
    content: { question: 'What does "fast" mean?', options: ['Slow', 'Quick', 'Loud', 'Cold'], correct: 'Quick', narrativeWrapper: 'The cheetah ran so _____ that no other animal could keep up.' },
    hint1: 'Think about a racing car.',
    hint2: 'It is the opposite of slow.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-easy-004', gameType: 'word-pop', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 2, memory: 1, reasoning: 1, speed: 1 },
    source: 'static',
    content: { question: 'What does "cold" mean?', options: ['Warm', 'Chilly', 'Bright', 'Heavy'], correct: 'Chilly', narrativeWrapper: 'She grabbed her coat because the morning air felt very _____.' },
    hint1: 'Think about winter weather.',
    hint2: 'Ice cream makes your hands feel this way.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-easy-005', gameType: 'word-pop', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 2, memory: 1, reasoning: 1, speed: 1 },
    source: 'static',
    content: { question: 'What does "bright" mean?', options: ['Dark', 'Shiny', 'Quiet', 'Rough'], correct: 'Shiny', narrativeWrapper: 'The sun was so _____ that she had to wear sunglasses.' },
    hint1: 'Think about a light bulb turned on.',
    hint2: 'It is the opposite of dark.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-easy-006', gameType: 'word-pop', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 2, memory: 1, reasoning: 1, speed: 1 },
    source: 'static',
    content: { question: 'What does "quiet" mean?', options: ['Loud', 'Silent', 'Fast', 'Rough'], correct: 'Silent', narrativeWrapper: 'The library was so _____ you could hear a pin drop.' },
    hint1: 'Think about the sound level when everyone is asleep.',
    hint2: 'It is the opposite of loud.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-easy-007', gameType: 'word-pop', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 2, memory: 1, reasoning: 1, speed: 1 },
    source: 'static',
    content: { question: 'What does "hot" mean?', options: ['Cold', 'Freezing', 'Burning', 'Dull'], correct: 'Burning', narrativeWrapper: 'The pizza from the oven was too _____ to touch right away.' },
    hint1: 'Think about how the sun feels on a summer afternoon.',
    hint2: 'It is the opposite of cold.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-easy-008', gameType: 'word-pop', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 2, memory: 1, reasoning: 1, speed: 1 },
    source: 'static',
    content: { question: 'What does "clean" mean?', options: ['Dirty', 'Tidy', 'Dark', 'Heavy'], correct: 'Tidy', narrativeWrapper: 'She washed all the dishes until everything was perfectly _____.' },
    hint1: 'Think about a room where everything is in its place.',
    hint2: 'It is the opposite of dirty.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-easy-009', gameType: 'word-pop', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 2, memory: 1, reasoning: 1, speed: 1 },
    source: 'static',
    content: { question: 'What does "wet" mean?', options: ['Dry', 'Damp', 'Warm', 'Bright'], correct: 'Damp', narrativeWrapper: 'He forgot his umbrella and arrived at school completely _____.' },
    hint1: 'Think about how you feel after jumping in a puddle.',
    hint2: 'It is the opposite of dry.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-easy-010', gameType: 'word-pop', difficulty: 'easy',
    cognitiveLoad: { vocabulary: 2, memory: 1, reasoning: 1, speed: 1 },
    source: 'static',
    content: { question: 'What does "strong" mean?', options: ['Weak', 'Powerful', 'Quiet', 'Thin'], correct: 'Powerful', narrativeWrapper: 'The _____ ox pulled the cart up the steep hill without stopping.' },
    hint1: 'Think about someone who can lift very heavy things.',
    hint2: 'It is the opposite of weak.',
    createdAt: '2026-05-19T00:00:00Z',
  },

  // ── MEDIUM ────────────────────────────────────────────────────────────────
  {
    id: 'wp-medium-001', gameType: 'word-pop', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 3, memory: 1, reasoning: 2, speed: 1 },
    source: 'static',
    content: { question: 'What does "curious" mean?', options: ['Bored', 'Eager to learn', 'Frightened', 'Clumsy'], correct: 'Eager to learn', narrativeWrapper: 'The _____ scientist stayed up all night to understand the strange glow.' },
    hint1: 'You feel this when you want to open a mystery box.',
    hint2: 'Cats are often described this way.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-medium-002', gameType: 'word-pop', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 3, memory: 1, reasoning: 2, speed: 1 },
    source: 'static',
    content: { question: 'What does "ancient" mean?', options: ['Very old', 'Very fast', 'Very tall', 'Very bright'], correct: 'Very old', narrativeWrapper: 'The archaeologist found an _____ coin buried under centuries of soil.' },
    hint1: 'Think about the pyramids in Egypt.',
    hint2: 'Dinosaurs lived in _____ times.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-medium-003', gameType: 'word-pop', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 3, memory: 1, reasoning: 2, speed: 1 },
    source: 'static',
    content: { question: 'What does "fragile" mean?', options: ['Strong', 'Easily broken', 'Very heavy', 'Very loud'], correct: 'Easily broken', narrativeWrapper: 'Handle the glass vase carefully — it is very _____.' },
    hint1: 'You see this word on boxes with eggs.',
    hint2: 'A bubble is very _____ — one touch and it pops.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-medium-004', gameType: 'word-pop', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 3, memory: 1, reasoning: 2, speed: 1 },
    source: 'static',
    content: { question: 'What does "swift" mean?', options: ['Heavy', 'Moving quickly', 'Very cold', 'Very sharp'], correct: 'Moving quickly', narrativeWrapper: 'The _____ hawk dived from the sky and caught the fish before it could escape.' },
    hint1: 'Think of a bird name that uses this word.',
    hint2: 'It means the same as rapid or speedy.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-medium-005', gameType: 'word-pop', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 3, memory: 1, reasoning: 2, speed: 1 },
    source: 'static',
    content: { question: 'What does "transparent" mean?', options: ['Very bright', 'You can see through it', 'Very thin', 'Completely silent'], correct: 'You can see through it', narrativeWrapper: 'The jellyfish had a _____ body — you could see its insides clearly.' },
    hint1: 'Glass windows are transparent.',
    hint2: 'If something is opaque, you cannot see through it. What is the opposite?',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-medium-006', gameType: 'word-pop', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 3, memory: 1, reasoning: 2, speed: 1 },
    source: 'static',
    content: { question: 'What does "enormous" mean?', options: ['Tiny', 'Gigantic', 'Noisy', 'Graceful'], correct: 'Gigantic', narrativeWrapper: 'The _____ blue whale stretched longer than three school buses.' },
    hint1: 'Think about something bigger than a house.',
    hint2: 'It means the same as huge or massive.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-medium-007', gameType: 'word-pop', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 3, memory: 1, reasoning: 2, speed: 1 },
    source: 'static',
    content: { question: 'What does "exhausted" mean?', options: ['Energetic', 'Completely tired', 'Very hungry', 'Very cold'], correct: 'Completely tired', narrativeWrapper: 'After the ten-mile hike, the children were utterly _____.' },
    hint1: 'Think about how you feel after running a very long race.',
    hint2: 'It is much stronger than just "tired".',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-medium-008', gameType: 'word-pop', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 3, memory: 1, reasoning: 2, speed: 1 },
    source: 'static',
    content: { question: 'What does "courageous" mean?', options: ['Fearful', 'Brave', 'Clumsy', 'Clever'], correct: 'Brave', narrativeWrapper: 'The _____ girl spoke up in front of the whole school when no one else would.' },
    hint1: 'You need this quality to face something scary.',
    hint2: 'The root word is "courage".',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-medium-009', gameType: 'word-pop', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 3, memory: 1, reasoning: 2, speed: 1 },
    source: 'static',
    content: { question: 'What does "peculiar" mean?', options: ['Ordinary', 'Strange', 'Beautiful', 'Generous'], correct: 'Strange', narrativeWrapper: 'It was _____ that every clock in the house stopped at exactly midnight.' },
    hint1: 'If something is peculiar, it makes you raise an eyebrow.',
    hint2: 'It means the same as unusual or odd.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-medium-010', gameType: 'word-pop', difficulty: 'medium',
    cognitiveLoad: { vocabulary: 3, memory: 1, reasoning: 2, speed: 1 },
    source: 'static',
    content: { question: 'What does "luminous" mean?', options: ['Dark', 'Glowing brightly', 'Very loud', 'Extremely cold'], correct: 'Glowing brightly', narrativeWrapper: 'The _____ deep-sea fish attracted its prey with the light on its head.' },
    hint1: 'The word comes from the Latin "lumen" meaning light.',
    hint2: 'A glow-in-the-dark sticker is luminous.',
    createdAt: '2026-05-19T00:00:00Z',
  },

  // ── HARD ──────────────────────────────────────────────────────────────────
  {
    id: 'wp-hard-001', gameType: 'word-pop', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 5, memory: 1, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: 'What does "ephemeral" mean?', options: ['Everlasting', 'Lasting only a short time', 'Very colourful', 'Extremely loud'], correct: 'Lasting only a short time', narrativeWrapper: 'A mayfly\'s life is _____ — it lives for just one day.' },
    hint1: 'The word comes from the Greek for "lasting a day".',
    hint2: 'Snowflakes and rainbows are beautiful but _____.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-hard-002', gameType: 'word-pop', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 5, memory: 1, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: 'What does "meticulous" mean?', options: ['Careless', 'Showing great attention to detail', 'Very fast', 'Extremely brave'], correct: 'Showing great attention to detail', narrativeWrapper: 'The watchmaker was _____, placing each tiny gear with perfect precision.' },
    hint1: 'A meticulous person never misses a single detail.',
    hint2: 'Think of someone who checks their homework three times.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-hard-003', gameType: 'word-pop', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 5, memory: 1, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: 'What does "benevolent" mean?', options: ['Cruel', 'Kind and generous', 'Extremely wise', 'Somewhat clumsy'], correct: 'Kind and generous', narrativeWrapper: 'The _____ king gave food to every person in the kingdom during the long winter.' },
    hint1: '"Bene" means good in Latin.',
    hint2: 'It means the same as charitable or magnanimous.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-hard-004', gameType: 'word-pop', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 5, memory: 1, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: 'What does "tenacious" mean?', options: ['Giving up easily', 'Holding firmly to a purpose', 'Very gentle', 'Extremely heavy'], correct: 'Holding firmly to a purpose', narrativeWrapper: 'Despite 100 failed attempts, the _____ inventor kept trying until the machine worked.' },
    hint1: 'A bulldog\'s grip is described as tenacious.',
    hint2: 'Think of the word "tenacity" — refusing to let go.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-hard-005', gameType: 'word-pop', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 5, memory: 1, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: 'What does "ambiguous" mean?', options: ['Perfectly clear', 'Open to more than one interpretation', 'Very ambitious', 'Extremely rare'], correct: 'Open to more than one interpretation', narrativeWrapper: 'The note left on the table was _____ — nobody could agree on what it meant.' },
    hint1: '"Ambi" means both in Latin.',
    hint2: 'If a sentence can mean two different things, it is _____.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-hard-006', gameType: 'word-pop', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 5, memory: 1, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: 'What does "oblivion" mean?', options: ['Great fame', 'A state of being forgotten or destroyed', 'Perfect order', 'Great wealth'], correct: 'A state of being forgotten or destroyed', narrativeWrapper: 'The once-great empire sank into _____ after its final defeat.' },
    hint1: '"Oblivion" shares its root with "oblivious" — not knowing or remembering.',
    hint2: 'A civilisation that no one remembers has fallen into _____.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-hard-007', gameType: 'word-pop', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 5, memory: 1, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: 'What does "paradox" mean?', options: ['A simple truth', 'A contradictory yet true statement', 'A type of scientific law', 'A persuasive argument'], correct: 'A contradictory yet true statement', narrativeWrapper: '"I always lie" is a classic _____ — if it\'s true, it must be false.' },
    hint1: '"Para" means against and "doxa" means belief in Greek.',
    hint2: 'Something that seems impossible but turns out to make sense.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-hard-008', gameType: 'word-pop', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 5, memory: 1, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: 'What does "eloquent" mean?', options: ['Clumsy with words', 'Fluent and persuasive in speech', 'Very knowledgeable', 'Extremely quiet'], correct: 'Fluent and persuasive in speech', narrativeWrapper: 'Her _____ defence moved the jury to tears and changed the verdict.' },
    hint1: 'From the Latin "eloqui" — to speak out clearly.',
    hint2: 'A skilled debater or orator is described this way.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-hard-009', gameType: 'word-pop', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 5, memory: 1, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: 'What does "pragmatic" mean?', options: ['Idealistic', 'Focused on practical results', 'Highly theoretical', 'Extremely cautious'], correct: 'Focused on practical results', narrativeWrapper: 'The _____ engineer skipped long debates and went straight to building a prototype.' },
    hint1: 'A pragmatic person asks "will it work?" rather than "is it perfect?".',
    hint2: 'The opposite is someone who only thinks in theory.',
    createdAt: '2026-05-19T00:00:00Z',
  },
  {
    id: 'wp-hard-010', gameType: 'word-pop', difficulty: 'hard',
    cognitiveLoad: { vocabulary: 5, memory: 1, reasoning: 3, speed: 1 },
    source: 'static',
    content: { question: 'What does "venerable" mean?', options: ['Inexperienced', 'Deserving great respect due to age or wisdom', 'Extremely powerful', 'Very modern'], correct: 'Deserving great respect due to age or wisdom', narrativeWrapper: 'The _____ professor had guided students at the university for over fifty years.' },
    hint1: 'From the Latin "venerari" — to revere.',
    hint2: 'Very old institutions and very wise elders are both described this way.',
    createdAt: '2026-05-19T00:00:00Z',
  },
]
